name: python2
channels:
  - conda-forge
dependencies:
  - python=2.7
  - libgdal=2.2.2
  - numpy=1.16.1  
  - pyproj=2.2.2  
  - proj4=4.9.3
  - gdal=2.2.2
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas=0.24.2
  - geopandas=0.6.3
  - mpi4py=3.0.3
  - folium
  - Cython
  - netCDF4
  - scipy
  - affine

