name: python2
channels:
  - conda-forge
  - default
dependencies:
  - python=2.7
  - gdal
  - geopandas
  - pandas=0.24.2
  - pip:
    - numpy=1.16.1  
    - pyproj
    - proj4
    - libgdal=2.2.2
    - gdal=2.2.2
    - psutil
    - toolz
    - matplotlib
    - fiona=1.8.13.post1
    - mpi4py=3.0.3
    - folium
    - Cython
    - netCDF4
    - scipy
    - affine

